apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkin
  namespace: k8
  labels:
    app: myapp
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: jenkins/jenkins:lts  # Replace with your Docker image
        ports:
        - containerPort: 8080

