apiVersion: v1
kind: Service
metadata:
  name: jenkin-service
  namespace: k8
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080  # Port for external access
      targetPort: 8080  # The port inside the pod
  type: ClusterIP  # For cloud environments (like AWS, GCP)

