---
- name: test
  hosts: localhost
  gather_facts: false
  connection: local


  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present
