---
- name: Delete  Application from Kubernetes
  hosts: localhost
  tasks:

    - name: Delete all Deployment from specified namespace
      k8s:
         api_version: apps/v1
         namespace: k8
         kind: Deployment
         delete_all: true
         state: absent
    - name: Remove an existing Service object
      k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: k8
        name: jenkin-service

    - name: delete a k8s namespace
      k8s:
        name: k8
        api_version: v1
        kind: Namespace
        state: absent
